title: Harsha's Blog
name: "Sriharsha's tech blog"
author: Sriharsha
twitter_username: Sriharshahatwar
baseurl: "/Sriharsha-blog"
description: Document my learning and personal experience.
profile_url: "http://Sriharsha-hatwar.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: jekyll-theme-cayman